/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : BookingStatus,
  'serviceName' : string,
  'customer' : Principal,
  'date' : string,
  'timestamp' : Time,
}
export type BookingStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export interface CustomerProfile {
  'principal' : Principal,
  'displayName' : string,
  'email' : [] | [string],
  'registrationTimestamp' : Time,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBooking' : ActorMethod<[string, string], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [CustomerProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerBookings' : ActorMethod<[], Array<Booking>>,
  'getCustomerProfile' : ActorMethod<[], [] | [CustomerProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [CustomerProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerCustomer' : ActorMethod<[string, [] | [string]], undefined>,
  'saveCallerUserProfile' : ActorMethod<[CustomerProfile], undefined>,
  'updateBookingStatus' : ActorMethod<[bigint, BookingStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];