/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const CustomerProfile = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'registrationTimestamp' : Time,
});
export const BookingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : BookingStatus,
  'serviceName' : IDL.Text,
  'customer' : IDL.Principal,
  'date' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBooking' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(CustomerProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getCustomerProfile' : IDL.Func([], [IDL.Opt(CustomerProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(CustomerProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerCustomer' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'saveCallerUserProfile' : IDL.Func([CustomerProfile], [], []),
  'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const CustomerProfile = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'registrationTimestamp' : Time,
  });
  const BookingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : BookingStatus,
    'serviceName' : IDL.Text,
    'customer' : IDL.Principal,
    'date' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBooking' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(CustomerProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getCustomerProfile' : IDL.Func([], [IDL.Opt(CustomerProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(CustomerProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerCustomer' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'saveCallerUserProfile' : IDL.Func([CustomerProfile], [], []),
    'updateBookingStatus' : IDL.Func([IDL.Nat, BookingStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };